#!/bin/bash

set -eu -o pipefail

# Redirect output to stderr.
exec 1>&2

output=$(git clang-format --diff --staged)
if [[ "$output" != "" && "$output" != "no modified files to format" ]]; then
  echo Code formatting changed some files, please review.
  exit 1
fi
